[package]
edition = "2021"
name = "hello_world"
description = "A minimal example of application development with GPUI Component."
publish = false
version = "0.4.0-preview2"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui-component = { workspace = true }

[lints]
workspace = true
